name: Cypress E2E and Integration Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CHAIN: "mumbai"
      NEXT_PUBLIC_THIRDWEB_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_THIRDWEB_CLIENT_ID }}
      NEXT_PUBLIC_THIRDWEB_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_THIRDWEB_SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run cypress E2E tests
      - name: Run Cypress E2E Testing
        uses: cypress-io/github-action@v4.1.0
        with:
          working-directory: webapp
          install-command: yarn install
          build: yarn build
          start: yarn start
          wait-on: "http://localhost:3000"

      #Run cypress component tests
      - name: Run Cypress Component Testing
        uses: cypress-io/github-action@v4.1.0
        with:
          working-directory: webapp
          install: false
          start: yarn next start -p 3001
          wait-on: "http://localhost:3001"
          component: true

      # Save screenshots on fail
      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ui/cypress/screenshots

      # Save test run videos, always
      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: ui/cypress/videos
